# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52131593b8a32cba851631220afe3cb3281b8cbd1d808708c1954a62312697b50d0a1e4c0b0bdcd07e03769dc9b9f88c15255569c7139934b20bfbfeb70a3fda

test:
  secret_key_base: 06bb5182bfc74f54cc6d73b39a74f02537e76214539bf70fe7d2bf42606e07ff99fde64111c4fbb09aa95e9f8ec6a03e307c628e7a3cf31b8c67c2decf35a764

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
